# Use zsh's path array, and this will remove duplicates.
# Note that zsh automatically turns $path into $PATH.
typeset -U path

path=($path ~/.rvm/bin)
path=($path ~/.emacs.d/bin/)
path=($path ~/bin/)
path=($path ~/.cargo/bin/)
path=($path ~/.local/bin/)

# If on Mac with Homebrew
if [ -d "/opt/homebrew" ]; then
  # Which Homebrew things do I want to include / override the default MacOS versions?
  path=(/opt/homebrew/opt/python/libexec/bin $path)
  path=(/opt/homebrew/opt/findutils/libexec/gnubin $path)
  path=(/opt/homebrew/anaconda3/bin $path)

  # And finally include the main non-conflicting Homebrew commands in the path
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

export EDITOR="vim"
export VISUAL=$EDITOR
export GIT_EDITOR=$EDITOR

export PAGER="less"

export BROWSER="firefox"

# Make Wine behave like 32 bit windows
export WINEARCH=win32

# Hide all Wine output on the command line
export WINEDEBUG=-all

# Force Libreoffice to use GTK even in KDE -- seems better now
#export SAL_USE_VCLPLUGIN=gtk

# If on WSL...
if [[ $(grep microsoft /proc/version >/dev/null 2>&1) ]]; then
  export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
  export LIBGL_ALWAYS_INDIRECT=1
fi

# Completions
if type brew &>/dev/null; then
 FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
 FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
 autoload -Uz compinit
 compinit
fi

