# Where the zsh configuration is stored
zsh_config_dir=~/.zsh

# Load Antigen
source $zsh_config_dir/antigen/antigen.zsh

# Load my Antigen plugins
source $zsh_config_dir/my-antigen-config.zsh

# For some annoying reason, oh-my-zsh sets this by default. Override that.
unsetopt share_history

# Set zsh's DEFAULT_USER if it is in the given list.
# Zsh will then hide it from the prompt.
# Other users will be shown as normal.
source $zsh_config_dir/set_default_user "pete|lewisp"

# Load aliases
source $zsh_config_dir/aliases

# Just for fun
function fractal {
   local lines columns colour a b p q i pnew
   ((columns=COLUMNS-1, lines=LINES-1, colour=0))
   for ((b=-1.5; b<=1.5; b+=3.0/lines)) do
     for ((a=-2.0; a<=1; a+=3.0/columns)) do
       for ((p=0.0, q=0.0, i=0; p*p+q*q < 4 && i < 32; i++)) do
         ((pnew=p*p-q*q+a, q=2*p*q+b, p=pnew))
       done
       ((colour=(i/4)%8))
       echo -n "\\e[4${colour}m "
     done
     echo
   done
}


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

